# Generated by Django 4.2.5 on 2023-10-18 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name_plural': 'Projects'},
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('quotation_info', models.TextField()),
                ('service_required', models.CharField(choices=[('cctv', 'CCTV Installation'), ('solar', 'Solar Installation'), ('home', 'Home Automation'), ('electrical', 'Electrical Wiring')], max_length=20)),
                ('uploaded_files', models.FileField(blank=True, null=True, upload_to='service_requests/')),
                ('status', models.CharField(default='pending', max_length=20)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
