# Generated by Django 4.2.6 on 2023-10-16 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projects",
            options={"verbose_name_plural": "Projects"},
        ),
    ]
