# Generated by Django 4.2.5 on 2023-11-26 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_alter_projects_options_servicerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='project_images/')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('finish_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_review', 'In Review'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_review', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
