# Generated by Django 4.2.6 on 2023-10-18 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_projects_options"),
        ("projects", "0002_alter_projects_options_servicerequest"),
    ]

    operations = []
