# Generated by Django 4.2.5 on 2023-11-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_serviceproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproject',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
