# Generated by Django 4.2.6 on 2023-11-26 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_merge_20231018_0959"),
        ("projects", "0004_serviceproject_location"),
    ]

    operations = []
