# Generated by Django 4.2.5 on 2023-12-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pecotechbd', '0004_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='quote_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
