# Generated by Django 4.2.6 on 2023-12-09 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pecotechbd", "0006_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="blog_post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="pecotechbd.blogpost",
            ),
        ),
    ]
